### ISSUE TITLE
Mismatched selenium/standalone-chrome with chromedriver

### ISSUE THREAD

**Issue by Zhu0914** [timoteostewart/dockerized-headfull-chrome-selenium#4]
In Dockerfile:
Replace ```FROM selenium/standalone-chrome:106.0 as build``` with ```FROM selenium/standalone-chrome:114.0 as build```

**Comment by timoteostewart** [comment]
@Zhu0914 Thank you! Please confirm that change doesn't break things, and then submit pull request for this and I will merge.

**Comment by timoteostewart** [comment]
Thanks @Zhu0914 . Issue addressed via 229ebd8.
